namespace iso8583_clearing_file_parser
{
    public class ISO8583Message
    {
        public string MTI { get; set; }
        public string BITMAP { get; set; }
        public string DE02 { get; set; }
        public string DE03 { get; set; }
        public string DE04 { get; set; }
        public string DE05 { get; set; }
        public string DE06 { get; set; }
        public string DE07 { get; set; }
        public string DE08 { get; set; }
        public string DE09 { get; set; }
        public string DE10 { get; set; }
        public string DE11 { get; set; }
        public string DE12 { get; set; }
        public string DE13 { get; set; }
        public string DE14 { get; set; }
        public string DE15 { get; set; }
        public string DE16 { get; set; }
        public string DE17 { get; set; }
        public string DE18 { get; set; }
        public string DE19 { get; set; }
        public string DE20 { get; set; }
        public string DE21 { get; set; }
        public string DE22 { get; set; }
        public string DE23 { get; set; }
        public string DE24 { get; set; }
        public string DE25 { get; set; }
        public string DE26 { get; set; }
        public string DE27 { get; set; }
        public string DE28 { get; set; }
        public string DE29 { get; set; }
        public string DE30 { get; set; }
        public string DE31 { get; set; }
        public string DE32 { get; set; }
        public string DE33 { get; set; }
        public string DE34 { get; set; }
        public string DE35 { get; set; }
        public string DE36 { get; set; }
        public string DE37 { get; set; }
        public string DE38 { get; set; }
        public string DE39 { get; set; }
        public string DE40 { get; set; }
        public string DE41 { get; set; }
        public string DE42 { get; set; }
        public string DE43 { get; set; }
        public string DE44 { get; set; }
        public string DE45 { get; set; }
        public string DE46 { get; set; }
        public string DE47 { get; set; }
        public string DE48 { get; set; }
        public string DE49 { get; set; }
        public string DE50 { get; set; }
        public string DE51 { get; set; }
        public string DE52 { get; set; }
        public string DE53 { get; set; }
        public string DE54 { get; set; }
        public string DE55 { get; set; }
        public string DE56 { get; set; }
        public string DE57 { get; set; }
        public string DE58 { get; set; }
        public string DE59 { get; set; }
        public string DE60 { get; set; }
        public string DE61 { get; set; }
        public string DE62 { get; set; }
        public string DE63 { get; set; }
        public string DE64 { get; set; }
        public string DE65 { get; set; }
        public string DE66 { get; set; }
        public string DE67 { get; set; }
        public string DE68 { get; set; }
        public string DE69 { get; set; }
        public string DE70 { get; set; }
        public string DE71 { get; set; }
        public string DE72 { get; set; }
        public string DE73 { get; set; }
        public string DE74 { get; set; }
        public string DE75 { get; set; }
        public string DE76 { get; set; }
        public string DE77 { get; set; }
        public string DE78 { get; set; }
        public string DE79 { get; set; }
        public string DE80 { get; set; }
        public string DE81 { get; set; }
        public string DE82 { get; set; }
        public string DE83 { get; set; }
        public string DE84 { get; set; }
        public string DE85 { get; set; }
        public string DE86 { get; set; }
        public string DE87 { get; set; }
        public string DE88 { get; set; }
        public string DE89 { get; set; }
        public string DE90 { get; set; }
        public string DE91 { get; set; }
        public string DE92 { get; set; }
        public string DE93 { get; set; }
        public string DE94 { get; set; }
        public string DE95 { get; set; }
        public string DE96 { get; set; }
        public string DE97 { get; set; }
        public string DE98 { get; set; }
        public string DE99 { get; set; }
        public string DE100 { get; set; }
        public string DE101 { get; set; }
        public string DE102 { get; set; }
        public string DE103 { get; set; }
        public string DE104 { get; set; }
        public string DE105 { get; set; }
        public string DE106 { get; set; }
        public string DE107 { get; set; }
        public string DE108 { get; set; }
        public string DE109 { get; set; }
        public string DE110 { get; set; }
        public string DE111 { get; set; }
        public string DE112 { get; set; }
        public string DE113 { get; set; }
        public string DE114 { get; set; }
        public string DE115 { get; set; }
        public string DE116 { get; set; }
        public string DE117 { get; set; }
        public string DE118 { get; set; }
        public string DE119 { get; set; }
        public string DE120 { get; set; }
        public string DE121 { get; set; }
        public string DE122 { get; set; }
        public string DE123 { get; set; }
        public string DE124 { get; set; }
        public string DE125 { get; set; }
        public string DE126 { get; set; }
        public string DE127 { get; set; }
        public string DE128 { get; set; }
    }
}
